<a href="https://colab.research.google.com/github/rosiekwon/smart_healthcare/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy
- 행렬, 벡터 연산을 위한 라이브러리
  - ndim : 배열의 차원
  - shape : 배열의 형태
  - size : 배열 내 원소들의 총 개수 
  - dtype : 배열 내의 원소의 자료형

In [23]:
#다차원 배열 (n-dimensional array)
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [27]:
#concatenate
r1= np.array([[1,2,3]])
r2= np.array([[4,5,6]])
#위아래로 붙이기
print(np.concatenate((r1,r2),axis=0))
print(np.vstack([r1,r2]))
print(np.r_[r1,r2])

#옆으로 붙이기
print(np.concatenate((r1,r2),axis=1))
print(np.hstack([r1,r2]))
print(np.c_[r1,r2])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]


In [28]:
#zero array
zero_arr = np.zeros(shape=(2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
#데이터 형태 변경
z2 = zero_arr.astype('int16')
print(z2.dtype)
print(z2)

int16
[[0 0 0]
 [0 0 0]]


In [33]:
#one array
one_arr = np.ones((2,3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
id = np.identity(n=5,dtype=np.int8)
id

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [36]:
#범위값 array
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

행렬의 사칙연산

In [39]:
#list 요소들의 합 구현
A = [[1,2,3],[4,5,6]]
B = [[4,5,6],[1,2,3]]
add = [[c+d for c, d in zip(a,b)] for a,b in zip(A,B)]
add

[[5, 7, 9], [5, 7, 9]]

In [40]:
a = np.array(A)
b = np.array(B)
a+b

array([[5, 7, 9],
       [5, 7, 9]])

In [42]:
#행렬의 곱
a = np.array(A)
b = np.array(B).reshape(3,2)
np.dot(a,b)

array([[22, 16],
       [58, 43]])

In [44]:
#broadcasting
a1 = np.array([[1,2,3],[14,15,16]])
a2 = np.array([1])
a3 = np.array([1,2,3])
a1,a2,a3

(array([[ 1,  2,  3],
        [14, 15, 16]]), array([1]), array([1, 2, 3]))

In [45]:
a1+a2+a3

array([[ 3,  5,  7],
       [16, 18, 20]])

In [49]:
#for문으로 행렬 곱 나타내기
A = [[1,2,3],[4,5,6]]
B = [[6,5],[4,3],[2,1]]
print(len(A),len(B))

res = [[0 for i in range(len(B[0]))] for _ in range(len(A))] # 2x2
for i in range(len(A)):
  for j in range(len(B[0])):
    for k in range(len(A[0])):
      res[i][j] += A[i][k] * B[k][j]
res

[[20, 14], [56, 41]]

n차원 배열의 슬라이싱

In [51]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
a[0], a[0,:], a[:,0]

(array([0, 1, 2]), array([0, 1, 2]), array([0, 3, 6]))

numpy statistic modules

In [56]:
arr = np.random.randn(1000)
np.max(arr), np.min(arr), np.mean(arr), np.var(arr), np.std(arr)

(3.097697951065557,
 -3.506062158441442,
 0.008254594730520533,
 1.0419975790896208,
 1.0207828266039847)

- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값 출력

In [57]:
np.linspace(0,100,5) 

array([  0.,  25.,  50.,  75., 100.])

In [58]:
np.logspace(0,100,5) 

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

numpy random module

In [62]:
#seed : 랜덤의 설정값
np.random.seed(1) 
res1 = np.random.randint(10,100,10)
res1

array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11])

In [69]:
arr = np.random.randint(0,10,(3,3))
arr

array([[9, 7, 6],
       [9, 1, 0],
       [1, 8, 8]])

In [66]:
#특정 조건
np.any(arr>5)

True

In [70]:
np.argmin(arr,axis=0) #각 column당 최솟값의 index

array([2, 1, 1])

In [73]:
print(np.where(arr<5,10,arr)) #조건에 맞는 원소를 10으로 값 변환, false일 경우 기존의 값으로
print(np.where(arr<5,1,0))

[[ 9  7  6]
 [ 9 10 10]
 [10  8  8]]
[[0 0 0]
 [0 1 1]
 [1 0 0]]


In [77]:
print(np.max(arr,1)) #row
print(np.max(arr))

[9 9 8]
9


Inner product
- numpy.inner : 1차원 또는 2차원 배열의 경우 내적을 위해 두번째 행렬을 전치 후 사용
- numpy.dot: 2차원의 배열의 경우 행렬 곱 연산을 수행하며 1차원 배열일 경우 벡터의 내적에 해당

In [84]:
a = np.random.randint(0,10,(2,4))
b = np.random.randint(0,10,(2,4))
a,b

(array([[3, 9, 8, 7],
        [3, 6, 5, 1]]), array([[9, 3, 4, 8],
        [1, 4, 0, 3]]))

In [85]:
np.dot(a,b.T)

array([[142,  60],
       [ 73,  30]])

In [86]:
np.inner(a,b)

array([[142,  60],
       [ 73,  30]])